backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "contabilidade"
    label: "Contabilidade"
    folder: "content/contabilidade"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Resumo", name: "summary", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "direito"
    label: "Direito"
    folder: "content/direito"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Resumo", name: "summary", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "cinema"
    label: "Cinema"
    folder: "content/cinema"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Resumo", name: "summary", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "arte"
    label: "Arte"
    folder: "content/arte"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Resumo", name: "summary", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "musica"
    label: "Música"
    folder: "content/musica"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Resumo", name: "summary", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "notas"
    label: "Notas"
    folder: "content/notas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Resumo", name: "summary", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
